"""adding difficulty column into the problems table.

Revision ID: 60b304a0e5c6
Revises: 3f18e21f1a66
Create Date: 2023-10-31 08:19:23.505581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60b304a0e5c6'
down_revision: Union[str, None] = '3f18e21f1a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('difficulty', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'difficulty')
    # ### end Alembic commands ###
